# -*- coding:utf-8 -*-

#类别代号：应用安全-0 源码安全-1 数据安全-2 漏洞-3 恶意行为-4 权限-5
#危险等级：高危-3 中危-2 低危-1 普通-0
AppItemDict = {
    '0_0' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'动态调试检查',
        'desc' : u'样本APP在运行时没有设置反调试校验等措施的话，会导致样本被专业人员恶意调试跟踪，导致敏感信息或关键逻辑暴露',
        'level' : u'中危',
        'harm' : u'APP在运行中被恶意调试跟踪，导致关键敏感数据泄露或关键逻辑暴露，会危及APP开发者的利益及APP使用者的相关权益',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取反调试校验或虚拟机运行监测等加固保护措施，导致APP在运行过程中允许动态调试',
        'adviseT' : u'使用鼎源APP加固方案的反调试加密功能，防止dex文件被动态调试',
    },

    '0_1' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'Activity安全',
        'desc' : u'评估样本是否存在将内部Activity暴露并存在可被利用漏洞',
        'level' : u'低危',
        'harm' : u'Activity被利用进行activity劫持或被权限攻击',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Activity劫持和攻击等加固保护措施，导致APP在运行过程中activity被劫持和攻击',
        'adviseT' : u'使用鼎源APP加固方案的防Activity劫持和攻击功能，防止activity被劫持和攻击',
    },

    '0_2' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'Broadcast Receiver安全',
        'desc' : u'评估样本是否存在Broadcast Receiver被监听、劫持',
        'level' : u'低危',
        'harm' : u'Broadcast Receiver被利用进行监听、劫持',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Broadcast Receiver监听、劫持等加固保护措施，导致APP在运行过程中Broadcast Receiver被劫持和监听',
        'adviseT' : u'使用鼎源APP加固方案的防Broadcast Receiver劫持和监听功能，防止activity被劫持和监听',
    },

    '0_3' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'Service安全',
        'desc' : u'评估样本是否存在Service被权限攻击',
        'level' : u'低危',
        'harm' : u'Service被权限攻击',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Service权限攻击等加固保护措施，导致APP在运行过程中Service被权限攻击',
        'adviseT' : u'使用鼎源APP加固方案的防Service权限攻击功能，防止Service被权限攻击',
    },

    '0_4' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'Content Provider安全',
        'desc' : u'评估样本是否存在Content Provider被权限攻击',
        'level' : u'低危',
        'harm' : u'Content Provider被权限攻击',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Content Provider权限攻击等加固保护措施，导致APP在运行过程中Content Provider被权限攻击',
        'adviseT' : u'使用鼎源APP加固方案的防Content Provider权限攻击功能，防止Content Provider被权限攻击',
    },

    '0_5' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'Intent安全',
        'desc' : u'评估样本是否存在Intent被权限攻击',
        'level' : u'低危',
        'harm' : u'Intent被权限攻击',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Intent权限攻击等加固保护措施，导致APP在运行过程中Intent被权限攻击',
        'adviseT' : u'使用鼎源APP加固方案的防Intent权限攻击功能，防止Intent被权限攻击',
    },

    '0_6' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'日志信息检查',
        'desc' : u'调试日志可能输出重要的日志文件，其中包含的信息可能导致客户端用户信息泄露，暴露客户端代码逻辑等，为发起攻击提供便利',
        'level' : u'低危',
        'harm' : u'调试日志可能暴露用户的重要日志信息，专业人员可能通过对日志信息进行分析窃取用户信息，破解客户端代码逻辑或者为其他调试跟踪等破解手段提供辅助信息',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP存在调试日志的调用，可能发生重要日志信息泄露的风险',
        'adviseT' : u'关闭调试日志调用，或者确保日志的输出使用了正确的级别，涉及敏感数据的日志信息在发布版本中被关闭',
    },

    '0_7' : {
        'type' : 0, # 0-自动 1-人工
        'name' : u'权限管理',
        'desc' : u'检测APP应用时，扫描权限中是否存在权限滥用问题和串谋攻击隐患',
        'level' : u'低危',
        'harm' : u'权限被滥用和串谋攻击隐患可能导致用户信息泄露的危害',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取权限检查等措施，导致APP中权限被滥用和串谋攻击隐患',
        'adviseT' : u'使用鼎源APP安全检测中的权限检测功能，检测权限滥用问题',
    },

    '0_8' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'日志信息渗透',
        'desc' : u'调试日志可能输出重要的日志文件，其中包含的信息可能导致客户端用户信息泄露，暴露客户端代码逻辑等，为发起攻击提供便利',
        'level' : u'高危',
        'harm' : u'调试日志可能暴露用户的重要日志信息，专业人员可能通过对日志信息进行分析窃取用户信息，破解客户端代码逻辑或者为其他调试跟踪等破解手段提供辅助信息',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP存在调试日志的调用，可能发生重要日志信息泄露的风险',
        'adviseT' : u'关闭调试日志调用，或者确保日志的输出使用了正确的级别，涉及敏感数据的日志信息在发布版本中被关闭',
    },

    '0_9' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'界面劫持',
        'desc' : u'评估样本是否存在将内部Activity暴露并存在可被利用漏洞，是否存在Activity被劫持的问题',
        'level' : u'高危',
        'harm' : u'Activity被利用进行Activity劫持',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在开发过程中或生成之后，没有对自身采取防Activity劫持等加固保护措施，导致APP在运行过程中Activity被劫持',
        'adviseT' : u'使用鼎源APP加固方案的防Activity劫持功能，防止Activity被劫持',
    },

    '0_10' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'模拟器检测',
        'desc' : u'利用模拟器运行样本程序',
        'level' : u'高危',
        'harm' : u'模拟器可以运行程序，会导致程序可以进行调试，导致程序信息泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'在模拟器环境下运行程序，可以对程序进行调试，导致程序的逻辑信息泄露等问题',
        'adviseT' : u'使用鼎源APP加固方案的防模拟器检测功能，防止程序在模拟器上运行',
    },

    '0_11' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'进程保护',
        'desc' : u'检测APP应用时，检测应用是否具备抵抗进程注入的能力。',
        'level' : u'高危',
        'harm' : u'APP应用不具有进程保护功能则容易被恶意调试和注入，导致APP数据和核心算法被窃取或篡改',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'',
        'adviseT' : u'',
    },

    '0_12' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'动态调试渗透',
        'desc' : u'检测APP应用时，检测程序是否具备抵抗动态调试的能力（Java层和Native层）。',
        'level' : u'高危',
        'harm' : u'APP应用没有或者防动态调试的能力太弱会导致APP的数据和核心算法会被通过动态调试手段窃取或篡改',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'',
        'adviseT' : u'',
    },

    '0_13' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'支付控制',
        'desc' : u'检查应用支付时是否需要输入支付密码，是否有错误支付密码尝试次数限制',
        'level' : u'高危',
        'harm' : u'如果应用在支付时不需要输入支付密码或者没有密码尝试次数限制会导致账户的不安全',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'',
        'adviseT' : u'',
    },

    '0_14' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'登录控制',
        'desc' : u'检测APP应用时，检查应用登录时是否需要输入登录密码，登录时是否有错误密码尝试次数限制',
        'level' : u'高危',
        'harm' : u'用户名和密码等敏感数据会泄露，导致用户权益受损害',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '0_15' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'支付密码设置',
        'desc' : u'检查应用中登录密码、支付密码是否采用不同安全级别的管理',
        'level' : u'高危',
        'harm' : u'用户名和密码和支付密码等敏感数据会泄露，导致用户权益受损害',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '0_16' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'双因子认证',
        'desc' : u'检查应用在大额支付、重要信息修改操作时是否采用除密码以外的安全认证机制',
        'level' : u'高危',
        'harm' : u'不采用双因子认证的话，对敏感操作的保护强度不够，容易导致重要操作安全强度不够，在操作过程中导致敏感信息泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '0_17' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'超时重新授权',
        'desc' : u'检查应用是否具备会话超时后要求重新授权的机制',
        'level' : u'高危',
        'harm' : u'不具备会话超时后要求重新授权的机制的话，会导致使用过期会话信息进行连接等非法操作，容易引起敏感信息的泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '0_18' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'密码强度',
        'desc' : u'检查应用的密码是否可以包含除字母和数字外的其他字符，密码长度是否可以多余8位',
        'level' : u'高危',
        'harm' : u'密码强度不够会导致密码被暴力破解方式窃取，导致用户信息泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '0_19' : {
        'type' : 1, # 0-自动 1-人工
        'name' : u'测试数据包含',
        'desc' : u'检查应用安装文件中是否包含测试数据（包含冗余文件和冗余说明，其中冗余文件包括：含有通信地址等敏感信息的配置文件、含有Java代码的备份文件、测试文件、与应用无关的冗余资源文件等；冗余说明包括：脚本代码中的功能说明、发布者信息、注释掉的代码块等，以及其他文本中出现的冗余说明）',
        'level' : u'中危',
        'harm' : u'测试数据或冗余信息会为恶意分析人员提供分析线索，提高应用被破解的风险概率',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'',
        'adviseT' : u'',
    },
}

SourceItemDict = {
    '1_0' : {
        'type' : 0,
        'name' : u'程序签名校验检查',
        'desc' : u'未对签名进行校验，可能该APP是经过二次打包等存在不安全因素的APP，如果用户进行安装，可能存在泄露用户信息风险',
        'level' : u'高危',
        'harm' : u'未进行签名校验，可能存在该APP不是原始版APP，可能该APP存在不安全的因素，如果用户使用，存在泄露用户私密信息的风险',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'攻击者在获得该APP源码进行加工之后，可能伪造该APP原来的签名进行签名，如果未进行签名校验，可能导致使用该APP的用户信息存在不安全隐患',
        'adviseT' : u'使用具有签名校验功能的加密加固工具对APP中的签名信息进行校验',
    },

    '1_1' : {
        'type' : 0,
        'name' : u'完整性校验检查',
        'desc' : u'通过外部白盒或黑盒对原有安全应用查看是否存在插入广告风险',
        'level' : u'高危',
        'harm' : u'二次打包可对应用进行广告插入和篡改，造成用户信息泄露，进入危险网页等危害，严重破坏用户体验和使用安全',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'没有对APP进行加固保护，使攻击者可以很容易的反编译APP进行二次打包',
        'adviseT' : u'使用鼎源APP加固方案进行加固',
    },

    '1_2' : {
        'type' : 0,
        'name' : u'代码混淆检查',
        'desc' : u'APP代码未保护，可能面临被反编译的风险。反编译的结果是应用程序的代码，这样就暴露了客户端的所有逻辑。攻击者可以利用这些信息窃取客户端的敏感数据或对服务器接口发起攻击',
        'level' : u'高危',
        'harm' : u'APP代码容易被反编译工具逆向分析并进一步进行逻辑或数据的篡改，给APP开发者或用户带来直接或间接的损失',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP未使用加固保护。该APP代码未进行混淆处理，可以被反编译后获取源代码',
        'adviseT' : u'使用鼎源APP加固方案的防反编译功能，防止应用被反编译',
    },

    '1_3' : {
        'type' : 0,
        'name' : u'反编译防范检测',
        'desc' : u'APP代码未保护，可能面临被反编译的风险。反编译的结果是应用程序的代码，这样就暴露了客户端的所有逻辑。攻击者可以利用这些信息窃取客户端的敏感数据或对服务器接口发起攻击',
        'level' : u'高危',
        'harm' : u'APP代码容易被反编译工具逆向分析并进一步进行逻辑或数据的篡改，给APP开发者或用户带来直接或间接的损失',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP未使用加固保护。该APP代码进行了混淆处理，但较易被破解。该APK可以被反编译后获取源代码',
        'adviseT' : u'使用鼎源APP加固方案的防反编译功能，防止应用被反编译',
    },

    '1_4' : {
        'type' : 0,
        'name' : u'资源文件保护检查',
        'desc' : u'APP中的资源文件没有进行加密保护措施的保护，极易被反编译工具破解逆向，生成明文的资源文件代码',
        'level' : u'中危',
        'harm' : u'APP中的资源文件泄露可以方便专业人员对APP的关键资源进行破解分析，从而进一步分析APP内部逻辑或提取APP关键数据，导致APP中的其他关键敏感数据和重要逻辑泄露或暴露',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在生成之后对资源文件没有做过加密保护等加固和防反编译的措施，极易导致资源文件被破解逆向分析',
        'adviseT' : u'使用具有资源文件防反编译功能的加密加固工具对APP中的资源文件进行加密',
    },

    '1_5' : {
        'type' : 0,
        'name' : u'硬编码-密码敏感词编码检查',
        'desc' : u'应用中存在硬编码的敏感信息或关键信息等',
        'level' : u'中危',
        'harm' : u'用户名和密码等敏感数据会泄露，导致用户权益受损害',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于不安全的编码习惯导致未加保护的敏感信息或关键信息等直接硬编码与应用中',
        'adviseT' : u'对未加保护的敏感信息或关键信息等进行加密处理或存储于采取了加密措施的数据库中等',
    },

    '1_6' : {
        'type' : 0,
        'name' : u'硬编码-密钥敏感词编码检查',
        'desc' : u'应用中存在硬编码的敏感信息或关键信息等',
        'level' : u'中危',
        'harm' : u'密钥等敏感数据会泄露，导致用户权益受损害',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于不安全的编码习惯导致未加保护的敏感信息或关键信息等直接硬编码与应用中',
        'adviseT' : u'对未加保护的敏感信息或关键信息等进行加密处理或存储于采取了加密措施的数据库中等',
    },

    '1_7' : {
        'type' : 0,
        'name' : u'主配置文件保护检查',
        'desc' : u'主配置文件未经加密处理，使用户对反编译的代码的阅读和调试提供了方便，用户可以更简单快捷的读懂整个代码运行逻辑，进一步篡改破坏用户信息财产安全',
        'level' : u'中危',
        'harm' : u'未经安全处理的应用主配置文件，其中的启动项、activity、权限等可被轻易获得，从而进行权限的添加和更改等危害',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在生成之后对AndroidManifest.xml文件没有做过加密保护等加固和防反编译的措施，极易导致AndroidManifest.xml文件被破解逆向分析',
        'adviseT' : u'使用具有AndroidManifest.xml文件防反编译功能的加密加固工具对APP中的AndroidManifest.xml文件进行加密',
    },

    '1_8' : {
        'type' : 0,
        'name' : u'安全编码规范-调用ROOT权限检查',
        'desc' : u'检测APP应用时，描源码检测是否密码直接写在代码中，或者是否使用了专用密码输入法。',
        'level' : u'中危',
        'harm' : u'用户名和密码等敏感数据会泄露，导致用户权益受损害',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_9' : {
        'type' : 0,
        'name' : u'硬编码-敏感字符串检查',
        'desc' : u'应用中存在硬编码的敏感信息或关键信息等',
        'level' : u'低危',
        'harm' : u'硬编码的敏感信息或关键信息等容易被恶意利用或调试跟踪等',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于不安全的编码习惯导致未加保护的敏感信息或关键信息等直接硬编码与应用中',
        'adviseT' : u'对未加保护的敏感信息或关键信息等进行加密处理或存储于采取了加密措施的数据库中等',
    },

    '1_10' : {
        'type' : 0,
        'name' : u'安全编码规范-加密算法检查',
        'desc' : u'APP中没有使用加密算法的保护，极易被攻击者获取源码',
        'level' : u'低危',
        'harm' : u'APP中没有使用加密算法的保护，极易被攻击者获取源码',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP在生成时没有做过加密保护等措施，极易导致源码被破解逆向分析',
        'adviseT' : u'使用鼎源APP加固方案的Dex加密功能对APP进行加密',
    },

    '1_11' : {
        'type' : 0,
        'name' : u'安全编码规范-全反射调用检查',
        'desc' : u'反射允许运行中的程序对自身进行检查，并能直接操作程序的内部属性或方法',
        'level' : u'低危',
        'harm' : u'反射机制能够对应用进行调试',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'APP中的反射机制能够对应用进行调试，导致敏感信息或关键逻辑暴露',
        'adviseT' : u'使用鼎源APP加固方案的反调试加密功能',
    },

    '1_12' : {
        'type' : 0,
        'name' : u'安全编码规范-明文SQL语句检查',
        'desc' : u'android平台使用sqlite作为数据库，对于数据库查询，如果开发者采用字符串连接方式构造SQL语句，就会产生sql注入',
        'level' : u'低危',
        'harm' : u'产生SQL注入的危险',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'采用字符串连接方式构造SQL语句，就会产生SQL注入的风险',
        'adviseT' : u'injection防护方式和常规思路一致，使用参数化查询或者增加一个数组存储查询参数',
    },

    '1_13' : {
        'type' : 1,
        'name' : u'程序签名校验渗透',
        'desc' : u'对程序签名进行篡改，检测程序是否具有签名校验功能及签名校验功能的保护强度',
        'level' : u'高危',
        'harm' : u'没有签名校验功能保护的应用会被轻易篡改后二次打包运行',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_14' : {
        'type' : 1,
        'name' : u'完整性校验渗透',
        'desc' : u'通过篡改APP数据后二次打包等方式检测应用是否具有完整性校验功能及其保护强度',
        'level' : u'高危',
        'harm' : u'没有对APP完整性进行校验的话，应用的数据会被轻易篡改',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_15' : {
        'type' : 1,
        'name' : u'代码混淆渗透',
        'desc' : u'检查代码混淆强度，检验APP代码混淆的安全性',
        'level' : u'高危',
        'harm' : u'没有经过代码混淆或只进行过简单处理的代码混淆保护措施的APP会被恶意分析核心算法，导致敏感数据或信息的泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_16' : {
        'type' : 1,
        'name' : u'DEX保护强度渗透',
        'desc' : u'检测DEX文件是否经过加固保护，分析其加固保护的强度',
        'level' : u'高危',
        'harm' : u'没有进行加固保护或加固保护强度太弱的DEX文件会被轻易破解，导致程序敏感信息和核心算法泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_17' : {
        'type' : 1,
        'name' : u'SO保护强度渗透',
        'desc' : u'检测SO文件是否经过加固保护，分析其加固保护的强度',
        'level' : u'高危',
        'harm' : u'没有进行加固保护或加固保护强度太弱的SO文件会被轻易破解，导致程序敏感信息和核心算法泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_18' : {
        'type' : 1,
        'name' : u'资源文件保护渗透',
        'desc' : u'检测资源文件是否经过加固保护，分析其加固保护的强度',
        'level' : u'高危',
        'harm' : u'没有进行加固保护或加固保护强度太弱的资源文件会被轻易破解，导致程序敏感信息泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_19' : {
        'type' : 1,
        'name' : u'内存保护',
        'desc' : u'检测应用进程是否采取了内存保护措施及分析其保护措施的强度',
        'level' : u'高危',
        'harm' : u'没有采取内存保护措施或保护强度很弱的应用进程会被恶意分析人员通过内存DUMP等方式获取敏感信息或注入等手段篡改逻辑和数据',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_20' : {
        'type' : 1,
        'name' : u'业务敏感逻辑渗透',
        'desc' : u'检测符合应用特点的相关业务逻辑安全性，对其业务逻辑的安全性进行评估',
        'level' : u'高危',
        'harm' : u'业务逻辑安全性不高的应用，会导致在处理业务过程中的敏感信息泄露，对用户造成损失',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },

    '1_21' : {
        'type' : 1,
        'name' : u'反编译防范渗透',
        'desc' : u'检测应用是否采取了有效的防反编译保护措施，分析其保护强度',
        'level' : u'高危',
        'harm' : u'应用没有采取有效的防反编译保护措施或其保护强度不够的话会导致应用被恶意分析人员进行反编译等操作，造成应用敏感信息和核心逻辑的泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'由于存在一些需求，导致可能将密码写入代码中',
        'adviseT' : u'使用鼎源APP加固方案的代码混淆功能，防止源码被获取',
    },
}

DataItemDict = {
    '2_0' : {
        'type' : 0,
        'name' : u'应用数据任意备份',
        'desc' : u'检测应用是否存在数据被外部命令任意备份风险',
        'level' : u'高危',
        'harm' : u'adb backup容许任何一个能够打开USB 调试开关的人从Android手机中复制应用数据到外设，一旦应用数据被备份之后，所有应用数据都可被用户读取；adb restore容许用户指定一个恢复的数据来源（即备份的应用数据）来恢复应用程序数据的创建',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中没有显式将android:allowBackup设置为false',
        'adviseT' : u'将android:allowBackup显式设置为false',
    },

    '2_1' : {
        'type' : 0,
        'name' : u'存储数据检查',
        'desc' : u'检查本地数据库存储的文件是否采取加密措施',
        'level' : u'中危',
        'harm' : u'未采取加密措施，本地数据库可以被sqlite相关工具进行逆向分析，直接暴露用户的各种关键数据，例如用户名，密码',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中未采取加固措施对本地数据库文件进行保护',
        'adviseT' : u'对数据库文件采取加密保护措施，或使用其他隐蔽格式的存储方式',
    },

    '2_2' : {
        'type' : 0,
        'name' : u'远程数据通讯协议',
        'desc' : u'无线传输的数据能被第三方轻易截获，由于客户端与服务器之间的传输数据遵循通信协议指定的格式和内容类型，如果未使用加密措施，传输数据可被还原成网络层的数据包并进行解包分析，直接暴露用户的各种关键数据',
        'level' : u'中危',
        'harm' : u'未使用加密措施，传输数据可被还原成网络层的数据包并进行解包分析，直接暴露用户的各种关键数据，例如用户名，密码',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS等协议对传输数据进行加密保护',
    },

    '2_3' : {
        'type' : 0,
        'name' : u'Content Provider 目录遍历脆弱点',
        'desc' : u'Android Content Provider存在文件目录遍历安全漏洞，该漏洞源于对外暴露Content Provider组件的应用，没有对Content Provider组件的访问进行权限控制和对访问的目标文件的Content Query Uri进行有效判断，攻击者可以利用该应用暴露的Content Provider的openFile()接口进行文件目录遍历以达到访问任意可读文件的目的',
        'level' : u'中危',
        'harm' : u'文件目录遍历导致任意可读文件被非法访问',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'导出了不必要的Content Provider或者开启了没有必要的OpenFile()接口或者没有过滤限制跨域访问或者没有设置相应权限来控制内部应用通过Content Provider的数据共享',
        'adviseT' : u'将不必要导出的Content Provider设置为不导出或者去除没有必要的OpenFile()接口或者过滤限制跨域访问，对访问的目标文件的路径进行有效判断或者设置权限来进行内部应用通过Content Provider的数据共享',
    },

    '2_4' : {
        'type' : 0,
        'name' : u'Content Provider URI脆弱点',
        'desc' : u'检测是否存在暴露的Content Provider URI',
        'level' : u'中危',
        'harm' : u'通过暴露的Content Provider URI，攻击者可以获取到URI对应的数据，导致敏感信息泄露',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'导出了不必要的Content Provider',
        'adviseT' : u'关闭不必要的Content Provider',
    },

    '2_5' : {
        'type' : 1,
        'name' : u'密码专用键盘保护',
        'desc' : u'检查用户输入密码时是否使用了键位随机的非系统键盘',
        'level' : u'高危',
        'harm' : u'使用系统键盘会导致用户密码输入时被记录位置而分析出原始密码，引起用户密码泄露的问题',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_6' : {
        'type' : 1,
        'name' : u'敏感数据截获',
        'desc' : u'检查在用户输入密码、证件号或卡号过程中，信息是否可以被扫描内存工具明文获取',
        'level' : u'高危',
        'harm' : u'敏感信息被扫描内存工具明文获取会导致用户信息泄露等问题',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_7' : {
        'type' : 1,
        'name' : u'敏感数据残留',
        'desc' : u'检查应用运行过程中，内存是否残留明文的密码、证件号或手机号',
        'level' : u'高危',
        'harm' : u'敏感信息在内存中以明文残留会导致攻击者分析内存或DUMP进程数据等方式获取用户敏感信息',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_8' : {
        'type' : 1,
        'name' : u'存储数据渗透',
        'desc' : u'分析检测本地存储数据是否经过保护措施处理及其保护强度',
        'level' : u'高危',
        'harm' : u'本地存储数据没有经过保护措施处理或保护强度太弱，会导致本地存储数据被分析和破解',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_9' : {
        'type' : 1,
        'name' : u'数据访问控制',
        'desc' : u'检测数据是否仅被授权用户或应用进程访问',
        'level' : u'高危',
        'harm' : u'数据被非法用户或应用进程访问会导致敏感信息泄露等问题',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_10' : {
        'type' : 1,
        'name' : u'敏感数据加密',
        'desc' : u'检测是否对口令、密码、银行卡号等已本地保存的敏感信息进行加密处理，加密强度是否达到要求',
        'level' : u'高危',
        'harm' : u'敏感数据没有进行加密保护或加密保护强度太弱会导致敏感信息被破解和泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_11' : {
        'type' : 1,
        'name' : u'内存数据安全',
        'desc' : u'检测程序在运行过程中，内存中是否保存敏感数据，敏感数据是否进行加密处理，加密强度是否达到要求',
        'level' : u'高危',
        'harm' : u'内存中的敏感数据没有进过加密保护或保护强度太弱会导致敏感数据被破解和泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_12' : {
        'type' : 1,
        'name' : u'远程数据通信加密',
        'desc' : u'检测程序与服务器通信的敏感数据是否进行加密处理，加密强度是否达到要求',
        'level' : u'高危',
        'harm' : u'未使用加密措施或加密强度太弱，传输数据可被还原成网络层的数据包并进行解包分析，直接暴露用户的各种关键数据，例如用户名，密码',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_13' : {
        'type' : 1,
        'name' : u'数据传输完整性',
        'desc' : u'检测程序与服务器通信的敏感数据是否进行完整性校验，防止数据传输中断或被篡改',
        'level' : u'高危',
        'harm' : u'敏感数据没有完整性校验会遭受中间人攻击，导致传输的数据被篡改和被截取',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_14' : {
        'type' : 1,
        'name' : u'本地数据通讯安全',
        'desc' : u'检测程序与本地其他应用进程间的数据传输是否采取加密处理和权限控制',
        'level' : u'高危',
        'harm' : u'进程间数据传输没有采取加密处理或权限控制的话会导致其他非法进程对数据的截取和篡改',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_15' : {
        'type' : 1,
        'name' : u'转账安全性检测',
        'desc' : u'检查应用转账时，账号、密码、证件号或手机号是否可以被监听、窃取、篡改等',
        'level' : u'高危',
        'harm' : u'应用转账过程中的敏感信息被监听、窃取、篡改等会导致铭感信息泄露和篡改，给用户造成损失',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_16' : {
        'type' : 1,
        'name' : u'安装包中敏感信息加密',
        'desc' : u'检查应用安装文件是否包含明文证书、密钥、网络配置、业务脚本代码',
        'level' : u'高危',
        'harm' : u'应用安装文件中的明文敏感数据会包含敏感信息和核心逻辑，攻击者可以利用其分析应用核心算法和漏洞',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_17' : {
        'type' : 1,
        'name' : u'界面切换后面敏感信息需清空',
        'desc' : u'检查应用界面切换后，用户输入的用户名、密码、证件号、手机号、卡号或金额信息等是否被清空',
        'level' : u'高危',
        'harm' : u'界面切换后未清空的残留敏感数据会给攻击者提供获取敏感信息的机会，导致用户敏感信息泄露',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_18' : {
        'type' : 1,
        'name' : u'数据输入敏感数据显示',
        'desc' : u'检测敏感数据（如用户密码）输入时软件界面是否为非明文显示',
        'level' : u'中危',
        'harm' : u'敏感信息全部显示容易泄露，敏感信息操作过程中会被偷窥泄露等',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_19' : {
        'type' : 1,
        'name' : u'本地数据通讯权限检查',
        'desc' : u'检测是否开启了不必要的本地数据通讯权限',
        'level' : u'中危',
        'harm' : u'开启不必要的本地数据通讯权限会导致其他恶意应用使用该权限窃取本地敏感信息',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_20' : {
        'type' : 1,
        'name' : u'数据输出敏感数据显示',
        'desc' : u'检测应用对敏感信息进行显示（账号、密码、身份证号等）时是否对部分字段进行屏蔽',
        'level' : u'低危',
        'harm' : u'敏感信息全部显示容易泄露，敏感信息操作过程中会被偷窥泄露等',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },

    '2_21' : {
        'type' : 1,
        'name' : u'卸载清除',
        'desc' : u'检查应用是否能够完全卸载清除',
        'level' : u'低危',
        'harm' : u'应用卸载不完全的残留数据会为攻击者提供攻击线索或漏洞提示',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'该APP应用中使用了不安全的网络协议进行数据传输',
        'adviseT' : u'使用HTTPS协议对传输数据进行加密保护',
    },
}

VulItemDict = {
    '3_0' : {
        'type' : 0,
        'name' : u'电话拨打权限绕过漏洞检查',
        'desc' : u'CVE-2013-6272漏洞可挂断当前电话，拨打任意电话',
        'level' : u'高危',
        'harm' : u'没有申明call_phone权限的应用无需交互可以拨打任意电话。任意应用更可以挂断当前正在进行的通话，而用户对此毫不知情',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'应该在BroadcastReceiver导出在其标签中加上属性android:exported="false"，但是有时候开发人员漏掉了这个属性',
        'adviseT' : u'将BroadcastReceiver中的android:exported="false"',
    },

    '3_1' : {
        'type' : 0,
        'name' : u'反射漏洞注入风险',
        'desc' : u'通过数据库访问手段采用外部引用反射应用内部逻辑方式，可以通过该漏洞利用对应用进行注入操作，引发被非法监控或植入恶代行为',
        'level' : u'中危',
        'harm' : u'应用被注入植入恶意代码',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'反射机制能够对应用进行调试，可以通过该漏洞对应用进行注入恶意代码，导致用户信息不安全',
        'adviseT' : u'使用具有数据库加密功能的加固软件加密数据库，使数据存储安全',
    },

    '3_2' : {
        'type' : 0,
        'name' : u'选择漏洞注入风险',
        'desc' : u'通过数据库访问手段采用非法查询方式，可以通过该漏洞利用对应用进行注入操作，引发被非法监控或植入恶代行为',
        'level' : u'中危',
        'harm' : u'数据库被非法访问，数据库信息泄露',
        'score' : 2,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'对于数据库查询，如果采用字符串连接方式构造语句，就会产生漏洞注入风险',
        'adviseT' : u'增加一个数据存储查询参数或使用参数化查询',
    },

    '3_3' : {
        'type' : 0,
        'name' : u'内网测试信息残留',
        'desc' : u'风险描述',
        'level' : u'低危',
        'harm' : u'风险危害',
        'score' : 1,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'存在导致风险的因素',
        'adviseT' : u'采取加固措施',
    },
}

HarmItemDict = {
    '4_0' : {
        'type' : 1,
        'name' : u'广告检测',
        'desc' : u'检测应用中是否存在广告植入等恶意行为',
        'level' : u'高危',
        'harm' : u'恶意广告植入会影响用户体验，导致用户流失',
        'score' : 3,
        'result' : u'不存在风险',
        'analysis' : u'没有导致风险的因素',
        'detail' : u'无',
        'advise' : u'无',

        #存在风险下的注释
        'resultT' : u'存在风险',
        'analysisT' : u'存在导致风险的因素',
        'adviseT' : u'采取加固措施',
    },
}

PermissionItemDict = {
    '5_NONE' : {
        'type' : 0,
        'name' : u'无',
        'desc' : u'无',
        'level' : u'未知',
        'harm' : u'不详',
        'score' : 0,
        'result' : u'存在风险',
        'analysis' : u'无',
        'detail' : u'无',
        'advise' : u'如果没有使用该权限请关闭',
    },

    #权限名称用包含包名的全名称
    '5_android.permission.WRITE_SMS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_SMS',
        'desc' : u'写短信',
        'level' : u'高危',
        'harm' : u'应用将获得写短信的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_SMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RECEIVE_SMS' : {
        'type' : 0,
        'name' : u'android.permission.RECEIVE_SMS',
        'desc' : u'监控接收短信',
        'level' : u'高危',
        'harm' : u'应用将获得监控接收短信的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RECEIVE_SMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_CONTACTS' : {
        'type' : 0,
        'name' : u'android.permission.READ_CONTACTS',
        'desc' : u'读取联系人信息',
        'level' : u'高危',
        'harm' : u'应用将获得读取联系人信息的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_CONTACTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_SMS' : {
        'type' : 0,
        'name' : u'android.permission.READ_SMS',
        'desc' : u'读取短信',
        'level' : u'高危',
        'harm' : u'应用将获得读取短信的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_SMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SEND_SMS' : {
        'type' : 0,
        'name' : u'android.permission.SEND_SMS',
        'desc' : u'发送短信',
        'level' : u'高危',
        'harm' : u'应用将获得发送短信的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SEND_SMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_com.android.browser.permission.WRITE_HISTORY_BOOKMARKS' : {
        'type' : 0,
        'name' : u'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS',
        'desc' : u'写浏览器书签',
        'level' : u'高危',
        'harm' : u'应用将获得写浏览器书签的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_com.android.browser.permission.READ_HISTORY_BOOKMARKS' : {
        'type' : 0,
        'name' : u'com.android.browser.permission.READ_HISTORY_BOOKMARKS',
        'desc' : u'读取浏览器书签',
        'level' : u'中危',
        'harm' : u'应用将获得读取浏览器书签的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'com.android.browser.permission.READ_HISTORY_BOOKMARKS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_com.android.launcher.permission.INSTALL_SHORTCUT' : {
        'type' : 0,
        'name' : u'com.android.launcher.permission.INSTALL_SHORTCUT',
        'desc' : u'创建快捷方式',
        'level' : u'中危',
        'harm' : u'应用将获得创建快捷方式的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'com.android.launcher.permission.INSTALL_SHORTCUT',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BRICK' : {
        'type' : 0,
        'name' : u'android.permission.BRICK',
        'desc' : u'请求能够禁用设备',
        'level' : u'高危',
        'harm' : u'应用将获得请求能够禁用设备的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BRICK',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.INTERNET' : {
        'type' : 0,
        'name' : u'android.permission.INTERNET',
        'desc' : u'连接网络',
        'level' : u'高危',
        'harm' : u'应用将获得连接网络的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.INTERNET',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_PHONE_STATE' : {
        'type' : 0,
        'name' : u'android.permission.READ_PHONE_STATE',
        'desc' : u'读取电话状态',
        'level' : u'高危',
        'harm' : u'应用将获得读取电话状态的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_PHONE_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_EXTERNAL_STORAGE' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_EXTERNAL_STORAGE',
        'desc' : u'写外部存储器（如：SD卡）',
        'level' : u'高危',
        'harm' : u'应用将获得写外部存储器的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_EXTERNAL_STORAGE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_CHECKIN_PROPERTIES' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_CHECKIN_PROPERTIES',
        'desc' : u'允许读写访问 "properties"表在checkin数据库中，改值可以修改上传',
        'level' : u'中危',
        'harm' : u'应用将获得访问登记属性，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_CHECKIN_PROPERTIES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_LOCATION_EXTRA_COMMANDS' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
        'desc' : u'应用程序访问位置的额外命令',
        'level' : u'中危',
        'harm' : u'应用将获得访问位置的额外命令的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_MOCK_LOCATION' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_MOCK_LOCATION',
        'desc' : u'程序创建模拟位置',
        'level' : u'中危',
        'harm' : u'应用将获得程序创建模拟位置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_MOCK_LOCATION',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_NETWORK_STATE' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_NETWORK_STATE',
        'desc' : u'访问GSM网络有关信息',
        'level' : u'中危',
        'harm' : u'应用将获得访问GSM网络有关信息的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_NETWORK_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_SURFACE_FLINGER' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_SURFACE_FLINGER',
        'desc' : u'使用SurfaceFlinger底层特性',
        'level' : u'高危',
        'harm' : u'应用将获得使用SurfaceFlinger底层特性的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_SURFACE_FLINGER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BLUETOOTH' : {
        'type' : 0,
        'name' : u'android.permission.BLUETOOTH',
        'desc' : u'连接到已配对的蓝牙设备',
        'level' : u'中危',
        'harm' : u'应用将获得连接到已配对的蓝牙设备的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BLUETOOTH',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BLUETOOTH_ADMIN' : {
        'type' : 0,
        'name' : u'android.permission.BLUETOOTH_ADMIN',
        'desc' : u'程序发现和配对蓝牙设备',
        'level' : u'中危',
        'harm' : u'应用将获得程序发现和配对蓝牙设备的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BLUETOOTH_ADMIN',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BROADCAST_STICKY' : {
        'type' : 0,
        'name' : u'android.permission.BROADCAST_STICKY',
        'desc' : u'广播常用intents',
        'level' : u'高危',
        'harm' : u'应用将获得广播常用intents的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BROADCAST_STICKY',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CALL_PRIVILEGED' : {
        'type' : 0,
        'name' : u'android.permission.CALL_PRIVILEGED',
        'desc' : u'拨打任何号码，包含紧急号码无需通过拨号用户界面需要用户确认',
        'level' : u'高危',
        'harm' : u'应用将获得拨打任何号码，包含紧急号码无需通过拨号用户界面需要用户确认的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CALL_PRIVILEGED',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CHANGE_COMPONENT_ENABLED_STATE' : {
        'type' : 0,
        'name' : u'android.permission.CHANGE_COMPONENT_ENABLED_STATE',
        'desc' : u'改变其他组件的使能状态',
        'level' : u'高危',
        'harm' : u'应用将获得改变其他组件的使能状态的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CHANGE_COMPONENT_ENABLED_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CHANGE_CONFIGURATION' : {
        'type' : 0,
        'name' : u'android.permission.CHANGE_CONFIGURATION',
        'desc' : u'修改当前设置',
        'level' : u'高危',
        'harm' : u'应用将获得修改当前设置的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CHANGE_CONFIGURATION',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CHANGE_WIFI_STATE' : {
        'type' : 0,
        'name' : u'android.permission.CHANGE_WIFI_STATE',
        'desc' : u'改变Wi-Fi连接状态',
        'level' : u'中危',
        'harm' : u'应用将获得改变Wi-Fi连接状态的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CHANGE_WIFI_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CLEAR_APP_CACHE' : {
        'type' : 0,
        'name' : u'android.permission.CLEAR_APP_CACHE',
        'desc' : u'清除应用缓存',
        'level' : u'高危',
        'harm' : u'应用将获得清除应用缓存的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CLEAR_APP_CACHE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CLEAR_APP_USER_DATA' : {
        'type' : 0,
        'name' : u'android.permission.CLEAR_APP_USER_DATA',
        'desc' : u'清除用户设置',
        'level' : u'高危',
        'harm' : u'应用将获得清除用户设置的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CLEAR_APP_USER_DATA',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CONTROL_LOCATION_UPDATES' : {
        'type' : 0,
        'name' : u'android.permission.CONTROL_LOCATION_UPDATES',
        'desc' : u'允许无线模块启用禁止位置更新',
        'level' : u'中危',
        'harm' : u'应用将获得允许无线模块启用禁止位置更新的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CONTROL_LOCATION_UPDATES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DELETE_CACHE_FILES' : {
        'type' : 0,
        'name' : u'android.permission.DELETE_CACHE_FILES',
        'desc' : u'删除缓存文件',
        'level' : u'中危',
        'harm' : u'应用将获得删除缓存文件的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DELETE_CACHE_FILES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DELETE_PACKAGES' : {
        'type' : 0,
        'name' : u'android.permission.DELETE_PACKAGES',
        'desc' : u'删除包',
        'level' : u'高危',
        'harm' : u'应用将获得删除包的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DELETE_PACKAGES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DEVICE_POWER' : {
        'type' : 0,
        'name' : u'android.permission.DEVICE_POWER',
        'desc' : u'访问底层电源管理',
        'level' : u'中危',
        'harm' : u'应用将获得访问底层电源管理的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DEVICE_POWER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DISABLE_KEYGUARD' : {
        'type' : 0,
        'name' : u'android.permission.DISABLE_KEYGUARD',
        'desc' : u'禁用键盘锁',
        'level' : u'中危',
        'harm' : u'应用将获得禁用键盘锁的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DISABLE_KEYGUARD',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DUMP' : {
        'type' : 0,
        'name' : u'android.permission.DUMP',
        'desc' : u'从系统服务返回状态抓取信息',
        'level' : u'中危',
        'harm' : u'应用将获得从系统服务返回状态抓取信息的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DUMP',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.EXPAND_STATUS_BAR' : {
        'type' : 0,
        'name' : u'android.permission.EXPAND_STATUS_BAR',
        'desc' : u'应用在状态栏扩展或收缩',
        'level' : u'中危',
        'harm' : u'应用将获得应用在状态栏扩展或收缩的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.EXPAND_STATUS_BAR',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.FACTORY_TEST' : {
        'type' : 0,
        'name' : u'android.permission.FACTORY_TEST',
        'desc' : u'作为一个工厂测试程序',
        'level' : u'中危',
        'harm' : u'应用将获得作为一个工厂测试程序的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.FACTORY_TEST',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.FLASHLIGHT' : {
        'type' : 0,
        'name' : u'android.permission.FLASHLIGHT',
        'desc' : u'访问闪光灯',
        'level' : u'中危',
        'harm' : u'应用将获得访问闪光灯的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.FLASHLIGHT',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.FORCE_BACK' : {
        'type' : 0,
        'name' : u'android.permission.FORCE_BACK',
        'desc' : u'强制后退操作在顶层',
        'level' : u'中危',
        'harm' : u'应用将获得强制后退操作在顶层的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.FORCE_BACK',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.GET_ACCOUNTS' : {
        'type' : 0,
        'name' : u'android.permission.GET_ACCOUNTS',
        'desc' : u'访问帐户列表',
        'level' : u'中危',
        'harm' : u'应用将获得访问帐户列表的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.GET_ACCOUNTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.HARDWARE_TEST' : {
        'type' : 0,
        'name' : u'android.permission.HARDWARE_TEST',
        'desc' : u'允许访问硬件',
        'level' : u'中危',
        'harm' : u'应用将获得允许访问硬件的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.HARDWARE_TEST',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.INJECT_EVENTS' : {
        'type' : 0,
        'name' : u'android.permission.INJECT_EVENTS',
        'desc' : u'截获用户事件，如按键、触摸、轨迹球',
        'level' : u'高危',
        'harm' : u'应用将获得截获用户事件的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.INJECT_EVENTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.INSTALL_PACKAGES' : {
        'type' : 0,
        'name' : u'android.permission.INSTALL_PACKAGES',
        'desc' : u'安装packages',
        'level' : u'高危',
        'harm' : u'应用将获得安装packages的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.INSTALL_PACKAGES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MANAGE_APP_TOKENS' : {
        'type' : 0,
        'name' : u'android.permission.MANAGE_APP_TOKENS',
        'desc' : u'在窗口管理器中管理程序',
        'level' : u'中危',
        'harm' : u'应用将获得在窗口管理器中管理程序的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MANAGE_APP_TOKENS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.PERSISTENT_ACTIVITY' : {
        'type' : 0,
        'name' : u'android.permission.PERSISTENT_ACTIVITY',
        'desc' : u'设置其他的activities显示',
        'level' : u'中危',
        'harm' : u'应用将获得设置其他的activities显示的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.PERSISTENT_ACTIVITY',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.PROCESS_OUTGOING_CALLS' : {
        'type' : 0,
        'name' : u'android.permission.PROCESS_OUTGOING_CALLS',
        'desc' : u'监视、修改有关拨出电话的信息',
        'level' : u'中危',
        'harm' : u'应用将获得监视、修改有关拨出电话的信息的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.PROCESS_OUTGOING_CALLS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_CALENDAR' : {
        'type' : 0,
        'name' : u'android.permission.READ_CALENDAR',
        'desc' : u'读取用户日历数据',
        'level' : u'中危',
        'harm' : u'应用将获得读取用户日历数据的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_CALENDAR',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_FRAME_BUFFER' : {
        'type' : 0,
        'name' : u'android.permission.READ_FRAME_BUFFER',
        'desc' : u'抓屏或访问帧缓冲',
        'level' : u'中危',
        'harm' : u'应用将获得抓屏或访问帧缓冲的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_FRAME_BUFFER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_INPUT_STATE' : {
        'type' : 0,
        'name' : u'android.permission.READ_INPUT_STATE',
        'desc' : u'当前按键状态',
        'level' : u'中危',
        'harm' : u'应用将获得当前按键状态的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_INPUT_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_LOGS' : {
        'type' : 0,
        'name' : u'android.permission.READ_LOGS',
        'desc' : u'读取底层系统日志文件',
        'level' : u'中危',
        'harm' : u'应用将获得读取底层系统日志文件的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_LOGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_OWNER_DATA' : {
        'type' : 0,
        'name' : u'android.permission.READ_OWNER_DATA',
        'desc' : u'读取所有者数据',
        'level' : u'中危',
        'harm' : u'应用将获得读取所有者数据的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_OWNER_DATA',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_SYNC_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.READ_SYNC_SETTINGS',
        'desc' : u'读取同步设置',
        'level' : u'中危',
        'harm' : u'应用将获得读取同步设置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_SYNC_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_SYNC_STATS' : {
        'type' : 0,
        'name' : u'android.permission.READ_SYNC_STATS',
        'desc' : u'读取同步状态',
        'level' : u'中危',
        'harm' : u'应用将获得读取同步状态的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_SYNC_STATS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.REBOOT' : {
        'type' : 0,
        'name' : u'android.permission.REBOOT',
        'desc' : u'重新启动设备',
        'level' : u'中危',
        'harm' : u'应用将获得重新启动设备的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.REBOOT',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RECEIVE_BOOT_COMPLETED' : {
        'type' : 0,
        'name' : u'android.permission.RECEIVE_BOOT_COMPLETED',
        'desc' : u'接收到ACTION_BOOT_COMPLETED',
        'level' : u'中危',
        'harm' : u'应用将获得接收到ACTION_BOOT_COMPLETED的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RECEIVE_BOOT_COMPLETED',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RECEIVE_MMS' : {
        'type' : 0,
        'name' : u'android.permission.RECEIVE_MMS',
        'desc' : u'接收MMS彩信',
        'level' : u'中危',
        'harm' : u'应用将获得接收MMS彩信的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RECEIVE_MMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RECEIVE_WAP_PUSH' : {
        'type' : 0,
        'name' : u'android.permission.RECEIVE_WAP_PUSH',
        'desc' : u'接收WAP PUSH信息',
        'level' : u'中危',
        'harm' : u'应用将获得接收WAP PUSH信息的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RECEIVE_WAP_PUSH',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RECORD_AUDIO' : {
        'type' : 0,
        'name' : u'android.permission.RECORD_AUDIO',
        'desc' : u'录制音频',
        'level' : u'中危',
        'harm' : u'应用将获得录制音频的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RECORD_AUDIO',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.REORDER_TASKS' : {
        'type' : 0,
        'name' : u'android.permission.REORDER_TASKS',
        'desc' : u'排列任务',
        'level' : u'中危',
        'harm' : u'应用将获得排列任务的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.REORDER_TASKS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_APN_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_APN_SETTINGS',
        'desc' : u'写入APN设置',
        'level' : u'中危',
        'harm' : u'应用将获得写入APN设置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_APN_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_CALENDAR' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_CALENDAR',
        'desc' : u'写入用户日历数据',
        'level' : u'中危',
        'harm' : u'应用将获得写入用户日历数据的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_CALENDAR',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_CONTACTS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_CONTACTS',
        'desc' : u'写入联系人数据',
        'level' : u'中危',
        'harm' : u'应用将获得写入联系人数据的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_CONTACTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_GSERVICES' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_GSERVICES',
        'desc' : u'修改Google地图服务',
        'level' : u'中危',
        'harm' : u'应用将获得修改Google地图服务的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_GSERVICES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_OWNER_DATA' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_OWNER_DATA',
        'desc' : u'写入所有者数据',
        'level' : u'中危',
        'harm' : u'应用将获得写入所有者数据的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_OWNER_DATA',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_SETTINGS',
        'desc' : u'读取或写入系统设置',
        'level' : u'中危',
        'harm' : u'应用将获得读取或写入系统设置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_SYNC_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_SYNC_SETTINGS',
        'desc' : u'写入同步设置',
        'level' : u'中危',
        'harm' : u'应用将获得写入同步设置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_SYNC_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_com.android.voicemail.permission.ADD_VOICEMAIL' : {
        'type' : 0,
        'name' : u'com.android.voicemail.permission.ADD_VOICEMAIL',
        'desc' : u'增加语音邮件',
        'level' : u'中危',
        'harm' : u'应用将获得增加语音邮件的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'com.android.voicemail.permission.ADD_VOICEMAIL',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MOUNT_UNMOUNT_FILESYSTEMS' : {
        'type' : 0,
        'name' : u'android.permission.MOUNT_UNMOUNT_FILESYSTEMS',
        'desc' : u'挂载、反挂载外部文件系统',
        'level' : u'高危',
        'harm' : u'应用将获得挂载、反挂载外部文件系统的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MOUNT_UNMOUNT_FILESYSTEMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_FINE_LOCATION' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_FINE_LOCATION',
        'desc' : u'通过GPS芯片接收卫星的定位信息',
        'level' : u'中危',
        'harm' : u'应用将获取精确位置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_FINE_LOCATION',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CALL_PHONE' : {
        'type' : 0,
        'name' : u'android.permission.CALL_PHONE',
        'desc' : u'拨打电话',
        'level' : u'中危',
        'harm' : u'应用将获得拨打电话的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CALL_PHONE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.RESTART_PACKAGES' : {
        'type' : 0,
        'name' : u'android.permission.RESTART_PACKAGES',
        'desc' : u'重启其他程序',
        'level' : u'中危',
        'harm' : u'应用将获得重启其他程序的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.RESTART_PACKAGES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_WALLPAPER' : {
        'type' : 0,
        'name' : u'android.permission.SET_WALLPAPER',
        'desc' : u'设置桌面壁纸',
        'level' : u'中危',
        'harm' : u'应用将获得设置桌面壁纸的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_WALLPAPER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_COARSE_LOCATION' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_COARSE_LOCATION',
        'desc' : u'通过WiFi或移动基站的方式获取用户错略的经纬度信息',
        'level' : u'中危',
        'harm' : u'应用将获取错略位置的权限，可能被用于恶意行为',
        'score' : 2,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_COARSE_LOCATION',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCESS_WIFI_STATE' : {
        'type' : 0,
        'name' : u'android.permission.ACCESS_WIFI_STATE',
        'desc' : u'访问Wi-Fi网络状态信息',
        'level' : u'低危',
        'harm' : u'应用将获得访问Wi-Fi网络状态信息的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCESS_WIFI_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ADD_SYSTEM_SERVICE' : {
        'type' : 0,
        'name' : u'android.permission.ADD_SYSTEM_SERVICE',
        'desc' : u'发布系统级服务',
        'level' : u'低危',
        'harm' : u'应用将获得发布系统级服务的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ADD_SYSTEM_SERVICE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BATTERY_STATS' : {
        'type' : 0,
        'name' : u'android.permission.BATTERY_STATS',
        'desc' : u'更新手机电池统计信息',
        'level' : u'低危',
        'harm' : u'应用将获得更新手机电池统计信息的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BATTERY_STATS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BROADCAST_PACKAGE_REMOVED' : {
        'type' : 0,
        'name' : u'android.permission.BROADCAST_PACKAGE_REMOVED',
        'desc' : u'在删除应用程序包后广播提示消息',
        'level' : u'低危',
        'harm' : u'应用将获得在删除应用程序包后广播提示消息的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BROADCAST_PACKAGE_REMOVED',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CAMERA' : {
        'type' : 0,
        'name' : u'android.permission.CAMERA',
        'desc' : u'请求访问使用照相设备',
        'level' : u'低危',
        'harm' : u'应用将获得请求访问使用照相设备的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CAMERA',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.GET_PACKAGE_SIZE' : {
        'type' : 0,
        'name' : u'android.permission.GET_PACKAGE_SIZE',
        'desc' : u'获取任何package占用空间容量',
        'level' : u'低危',
        'harm' : u'应用将获取任何package占用空间容量的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.GET_PACKAGE_SIZE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.GET_TASKS' : {
        'type' : 0,
        'name' : u'android.permission.GET_TASKS',
        'desc' : u'获取有关当前或最近运行的任务信息',
        'level' : u'低危',
        'harm' : u'应用将获取有关当前或最近运行的任务信息的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.GET_TASKS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.INTERNAL_SYSTEM_WINDOW' : {
        'type' : 0,
        'name' : u'android.permission.INTERNAL_SYSTEM_WINDOW',
        'desc' : u'允许打开使用系统用户界面的窗口',
        'level' : u'低危',
        'harm' : u'应用将获得允许打开使用系统用户界面的窗口的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.INTERNAL_SYSTEM_WINDOW',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MODIFY_AUDIO_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.MODIFY_AUDIO_SETTINGS',
        'desc' : u'修改全局音频设置',
        'level' : u'低危',
        'harm' : u'应用将获得修改全局音频设置的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MODIFY_AUDIO_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_ACTIVITY_WATCHER' : {
        'type' : 0,
        'name' : u'android.permission.SET_ACTIVITY_WATCHER',
        'desc' : u'控制已经在全局系统中启动的activities',
        'level' : u'低危',
        'harm' : u'应用将获得控制已经在全局系统中启动的activities的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_ACTIVITY_WATCHER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_ANIMATION_SCALE' : {
        'type' : 0,
        'name' : u'android.permission.SET_ANIMATION_SCALE',
        'desc' : u'修改全局信息比例',
        'level' : u'低危',
        'harm' : u'应用将获得修改全局信息比例的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_ANIMATION_SCALE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_DEBUG_APP' : {
        'type' : 0,
        'name' : u'android.permission.SET_DEBUG_APP',
        'desc' : u'配置程序处于调试状态',
        'level' : u'低危',
        'harm' : u'应用将获得配置程序处于调试状态的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_DEBUG_APP',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_ORIENTATION' : {
        'type' : 0,
        'name' : u'android.permission.SET_ORIENTATION',
        'desc' : u'底层访问设置屏幕方向和实际旋转',
        'level' : u'低危',
        'harm' : u'应用将获得底层访问设置屏幕方向和实际旋转的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_ORIENTATION',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_PREFERRED_APPLICATIONS' : {
        'type' : 0,
        'name' : u'android.permission.SET_PREFERRED_APPLICATIONS',
        'desc' : u'修改列表参数',
        'level' : u'低危',
        'harm' : u'应用将获得修改列表参数的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_PREFERRED_APPLICATIONS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_PROCESS_FOREGROUND' : {
        'type' : 0,
        'name' : u'android.permission.SET_PROCESS_FOREGROUND',
        'desc' : u'强制当前程序运行到前台',
        'level' : u'低危',
        'harm' : u'应用将获得强制当前程序运行到前台的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_PROCESS_FOREGROUND',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_PROCESS_LIMIT' : {
        'type' : 0,
        'name' : u'android.permission.SET_PROCESS_LIMIT',
        'desc' : u'允许设置最大的运行进程数量',
        'level' : u'低危',
        'harm' : u'应用将获得允许设置最大的运行进程数量的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_PROCESS_LIMIT',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_TIME_ZONE' : {
        'type' : 0,
        'name' : u'android.permission.SET_TIME_ZONE',
        'desc' : u'设置时间区域',
        'level' : u'低危',
        'harm' : u'应用将获得设置时间区域的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_TIME_ZONE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.STATUS_BAR' : {
        'type' : 0,
        'name' : u'android.permission.STATUS_BAR',
        'desc' : u'打开、关闭或禁用状态栏及图标',
        'level' : u'低危',
        'harm' : u'应用将获得打开、关闭或禁用状态栏及图标的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.STATUS_BAR',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SUBSCRIBED_FEEDS_READ' : {
        'type' : 0,
        'name' : u'android.permission.SUBSCRIBED_FEEDS_READ',
        'desc' : u'访问订阅RSS Feed内容',
        'level' : u'低危',
        'harm' : u'应用将获得访问订阅RSS Feed内容的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SUBSCRIBED_FEEDS_READ',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SUBSCRIBED_FEEDS_WRITE' : {
        'type' : 0,
        'name' : u'android.permission.SUBSCRIBED_FEEDS_WRITE',
        'desc' : u'写入或修改订阅内容的数据库',
        'level' : u'高危',
        'harm' : u'应用将获得写入或修改订阅内容的数据库的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SUBSCRIBED_FEEDS_WRITE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.VIBRATE' : {
        'type' : 0,
        'name' : u'android.permission.VIBRATE',
        'desc' : u'访问振动设备',
        'level' : u'低危',
        'harm' : u'应用将获得访问振动设备的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.VIBRATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WAKE_LOCK' : {
        'type' : 0,
        'name' : u'android.permission.WAKE_LOCK',
        'desc' : u'使用WakeLocks使得进程在休眠时从屏幕消失',
        'level' : u'低危',
        'harm' : u'应用将获得使用WakeLocks使得进程在休眠时从屏幕消失的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WAKE_LOCK',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.READ_EXTERNAL_STORAGE' : {
        'type' : 0,
        'name' : u'android.permission.READ_EXTERNAL_STORAGE',
        'desc' : u'读取外部存储',
        'level' : u'低危',
        'harm' : u'应用将获得读取外部存储的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.READ_EXTERNAL_STORAGE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.DIAGNOSTIC' : {
        'type' : 0,
        'name' : u'android.permission.DIAGNOSTIC',
        'desc' : u'允许程序RW诊断资源',
        'level' : u'低危',
        'harm' : u'应用将获得允许程序RW诊断资源的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.DIAGNOSTIC',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CHANGE_NETWORK_STATE' : {
        'type' : 0,
        'name' : u'android.permission.CHANGE_NETWORK_STATE',
        'desc' : u'允许程序改变网络连接状态',
        'level' : u'高危',
        'harm' : u'应用将获得允许程序改变网络连接状态的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CHANGE_NETWORK_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MASTER_CLEAR' : {
        'type' : 0,
        'name' : u'android.permission.MASTER_CLEAR',
        'desc' : u'清除一切数据',
        'level' : u'高危',
        'harm' : u'应用将获得清除一切数据的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MASTER_CLEAR',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MODIFY_PHONE_STATE' : {
        'type' : 0,
        'name' : u'android.permission.MODIFY_PHONE_STATE',
        'desc' : u'允许修改话机状态，如电源，人机接口等',
        'level' : u'高危',
        'harm' : u'应用将获得允许修改话机状态，如电源，人机接口等的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MODIFY_PHONE_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_ALWAYS_FINISH' : {
        'type' : 0,
        'name' : u'android.permission.SET_ALWAYS_FINISH',
        'desc' : u'允许程序控制是否活动间接完成在处于后台时',
        'level' : u'低危',
        'harm' : u'应用将获得允许程序控制是否活动间接完成在处于后台时的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_ALWAYS_FINISH',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SET_WALLPAPER_HINTS' : {
        'type' : 0,
        'name' : u'android.permission.SET_WALLPAPER_HINTS',
        'desc' : u'允许程序设置壁纸hits',
        'level' : u'低危',
        'harm' : u'应用将获得允许程序设置壁纸hits的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SET_WALLPAPER_HINTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SIGNAL_PERSISTENT_PROCESSES' : {
        'type' : 0,
        'name' : u'android.permission.SIGNAL_PERSISTENT_PROCESSES',
        'desc' : u'允许程序请求发送信号到所有显示的进程中',
        'level' : u'高危',
        'harm' : u'应用将获得允许程序请求发送信号到所有显示的进程中的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SIGNAL_PERSISTENT_PROCESSES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.SYSTEM_ALERT_WINDOW' : {
        'type' : 0,
        'name' : u'android.permission.SYSTEM_ALERT_WINDOW',
        'desc' : u'允许一个程序打开窗口使用 TYPE_SYSTEM_ALERT，显示在其他所有程序的顶层',
        'level' : u'高危',
        'harm' : u'应用将获得显示在其他所有程序的顶层的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.SYSTEM_ALERT_WINDOW',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.ACCOUNT_MANAGER' : {
        'type' : 0,
        'name' : u'android.permission.ACCOUNT_MANAGER',
        'desc' : u'账户管理，获取账户验证信息',
        'level' : u'高危',
        'harm' : u'应用将获得账户验证信息的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.ACCOUNT_MANAGER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.AUTHENTICATE_ACCOUNTS' : {
        'type' : 0,
        'name' : u'android.permission.AUTHENTICATE_ACCOUNTS',
        'desc' : u'验证账户，允许一个程序通过账户验证方式访问账户管理ACCOUNT_MANAGER相关信息',
        'level' : u'高危',
        'harm' : u'应用将获得验证账户的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.AUTHENTICATE_ACCOUNTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BIND_APPWIDGET' : {
        'type' : 0,
        'name' : u'android.permission.BIND_APPWIDGET',
        'desc' : u'绑定小插件，允许一个程序告诉appWidget服务需要访问小插件的数据库',
        'level' : u'低危',
        'harm' : u'应用将获得绑定小插件的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BIND_APPWIDGET',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BIND_DEVICE_ADMIN' : {
        'type' : 0,
        'name' : u'android.permission.BIND_DEVICE_ADMIN',
        'desc' : u'绑定设备管理，请求系统管理员接收者receiver',
        'level' : u'低危',
        'harm' : u'应用将获得绑定设备管理的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BIND_DEVICE_ADMIN',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BIND_INPUT_METHOD' : {
        'type' : 0,
        'name' : u'android.permission.BIND_INPUT_METHOD',
        'desc' : u'绑定输入法，请求InputMethodService服务',
        'level' : u'低危',
        'harm' : u'应用将获得绑定输入法的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BIND_INPUT_METHOD',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BIND_REMOTEVIEWS' : {
        'type' : 0,
        'name' : u'android.permission.BIND_REMOTEVIEWS',
        'desc' : u'绑定RemoteView，必须通过RemoteViewsService服务来请求',
        'level' : u'低危',
        'harm' : u'应用将获得绑定RemoteView的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BIND_REMOTEVIEWS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BIND_WALLPAPER' : {
        'type' : 0,
        'name' : u'android.permission.BIND_WALLPAPER',
        'desc' : u'绑定壁纸，必须通过WallpaperService服务来请求',
        'level' : u'低危',
        'harm' : u'应用将获得绑定壁纸的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BIND_WALLPAPER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BROADCAST_SMS' : {
        'type' : 0,
        'name' : u'android.permission.BROADCAST_SMS',
        'desc' : u'收到短信时广播',
        'level' : u'高危',
        'harm' : u'应用将获得收到短信时广播的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BROADCAST_SMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.BROADCAST_WAP_PUSH' : {
        'type' : 0,
        'name' : u'android.permission.BROADCAST_WAP_PUSH',
        'desc' : u'WAP PUSH广播',
        'level' : u'高危',
        'harm' : u'应用将获得WAP PUSH广播的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.BROADCAST_WAP_PUSH',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CHANGE_WIFI_MULTICAST_STATE' : {
        'type' : 0,
        'name' : u'android.permission.CHANGE_WIFI_MULTICAST_STATE',
        'desc' : u'改变WiFi多播状态',
        'level' : u'高危',
        'harm' : u'应用将获得改变WiFi多播状态的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CHANGE_WIFI_MULTICAST_STATE',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CWJ_GROUP' : {
        'type' : 0,
        'name' : u'android.permission.CWJ_GROUP',
        'desc' : u'底层访问权限，允许CWJ账户组访问底层信息',
        'level' : u'高危',
        'harm' : u'应用将获得底层访问权限的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CWJ_GROUP',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.CELL_PHONE_MASTER_EX' : {
        'type' : 0,
        'name' : u'android.permission.CELL_PHONE_MASTER_EX',
        'desc' : u'手机优化大师扩展权限',
        'level' : u'高危',
        'harm' : u'应用将获得手机优化大师扩展权限的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.CELL_PHONE_MASTER_EX',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.GLOBAL_SEARCH' : {
        'type' : 0,
        'name' : u'android.permission.GLOBAL_SEARCH',
        'desc' : u'允许全局搜索',
        'level' : u'高危',
        'harm' : u'应用将获得允许全局搜索的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.GLOBAL_SEARCH',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.INSTALL_LOCATION_PROVIDER' : {
        'type' : 0,
        'name' : u'android.permission.INSTALL_LOCATION_PROVIDER',
        'desc' : u'安装定位提供',
        'level' : u'低危',
        'harm' : u'应用将获得安装定位提供的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.INSTALL_LOCATION_PROVIDER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.KILL_BACKGROUND_PROCESSES' : {
        'type' : 0,
        'name' : u'android.permission.KILL_BACKGROUND_PROCESSES',
        'desc' : u'结束后台进程，允许程序调用killBackgroundProcesses(String).方法结束后台进程',
        'level' : u'高危',
        'harm' : u'应用将获得结束后台进程的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.KILL_BACKGROUND_PROCESSES',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MANAGE_ACCOUNTS' : {
        'type' : 0,
        'name' : u'android.permission.MANAGE_ACCOUNTS',
        'desc' : u'允许程序管理AccountManager中的账户列表',
        'level' : u'高危',
        'harm' : u'应用将获得允许程序管理AccountManager中的账户列表的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MANAGE_ACCOUNTS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MTWEAK_USER' : {
        'type' : 0,
        'name' : u'android.permission.MTWEAK_USER',
        'desc' : u'允许mTweak用户访问高级系统权限',
        'level' : u'高危',
        'harm' : u'应用将获得允许mTweak用户访问高级系统权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MTWEAK_USER',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MTWEAK_FORUM' : {
        'type' : 0,
        'name' : u'android.permission.MTWEAK_FORUM',
        'desc' : u'允许使用mTweak社区权限',
        'level' : u'高危',
        'harm' : u'应用将获得允许使用mTweak社区权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MTWEAK_FORUM',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.MOUNT_FORMAT_FILESYSTEMS' : {
        'type' : 0,
        'name' : u'android.permission.MOUNT_FORMAT_FILESYSTEMS',
        'desc' : u'格式化可移动文件系统，比如格式化清空SD卡',
        'level' : u'高危',
        'harm' : u'应用将获得格式化可移动文件系统的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.MOUNT_FORMAT_FILESYSTEMS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.NFC' : {
        'type' : 0,
        'name' : u'android.permission.NFC',
        'desc' : u'允许程序执行NFC近距离通讯操作，用于移动支持',
        'level' : u'高危',
        'harm' : u'应用将获得允许程序执行NFC近距离通讯操作的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.NFC',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.com.android.alarm.permission.SET_ALARM' : {
        'type' : 0,
        'name' : u'android.permission.com.android.alarm.permission.SET_ALARM',
        'desc' : u'设置闹铃提醒',
        'level' : u'低危',
        'harm' : u'应用将获得设置闹铃提醒的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'com.android.alarm.permission.SET_ALARM',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.UPDATE_DEVICE_STATS' : {
        'type' : 0,
        'name' : u'android.permission.UPDATE_DEVICE_STATS',
        'desc' : u'更新设备状态',
        'level' : u'低危',
        'harm' : u'应用将获得更新设备状态的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.UPDATE_DEVICE_STATS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.USE_CREDENTIALS' : {
        'type' : 0,
        'name' : u'android.permission.USE_CREDENTIALS',
        'desc' : u'使用证书',
        'level' : u'高危',
        'harm' : u'应用将获得使用证书的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.USE_CREDENTIALS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.USE_SIP' : {
        'type' : 0,
        'name' : u'android.permission.USE_SIP',
        'desc' : u'使用SIP视频',
        'level' : u'低危',
        'harm' : u'应用将获得使用SIP视频的权限，可能被用于恶意行为',
        'score' : 1,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.USE_SIP',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
    '5_android.permission.WRITE_SECURE_SETTINGS' : {
        'type' : 0,
        'name' : u'android.permission.WRITE_SECURE_SETTINGS',
        'desc' : u'允许程序读写系统安全敏感的设置项',
        'level' : u'高危',
        'harm' : u'应用将获得允许程序读写系统安全敏感的设置项的权限，可能被用于恶意行为',
        'score' : 3,
        'result' : u'存在风险',
        'analysis' : u'在权限配置中可能设置开启了该权限项',
        'detail' : u'android.permission.WRITE_SECURE_SETTINGS',
        'advise' : u'如果应用中没有使用该权限建议将其设为关闭状态',
    },
}